package com.greymax.vkplayer.ui.update;

import javax.swing.*;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.File;
import java.net.URL;


public class ProgressDialog extends javax.swing.JDialog implements PropertyChangeListener {


    public ProgressDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(new ImageIcon(ProgressDialog.class.getResource("/resources/img/ico.png")).getImage());
        currentProgressBar.setMaximum(100);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        totalProgressBar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        currentProgressBar = new javax.swing.JProgressBar();
        fromLabel = new javax.swing.JLabel();
        toLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);

        totalProgressBar.setStringPainted(true);

        jLabel1.setText("Copying...");

        currentProgressBar.setStringPainted(true);

        fromLabel.setText("From:");

        toLabel.setText("To:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(toLabel))
//                                        .addComponent(currentProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                                        .addComponent(jLabel1)
                                        .addComponent(totalProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                                        .addComponent(fromLabel))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fromLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(toLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                .addComponent(currentProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(totalProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setMaximum(int val){
        totalProgressBar.setMaximum(val);
    }

    public void setCurrentValue(int val){
        totalProgressBar.setValue(val);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar currentProgressBar;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel toLabel;
    private javax.swing.JProgressBar totalProgressBar;
    // End of variables declaration//GEN-END:variables

    public void propertyChange(PropertyChangeEvent evt) {
        if("progress".equals(evt.getPropertyName())){
            setCurrentValue((Integer)evt.getNewValue());
            if((Integer)evt.getNewValue() == 100){
                dispose();
            }
        } else if("currentFrom".equals(evt.getPropertyName())){
            fromLabel.setText("From: " + ((URL)evt.getNewValue()).getPath());
        } else if("currentTo".equals(evt.getPropertyName())){
            toLabel.setText("To: " + ((File)evt.getNewValue()).getAbsolutePath());
        } else if ("currentProgress".equals(evt.getPropertyName())){
            currentProgressBar.setValue((Integer)evt.getNewValue());
        }
    }
}

